// AUTO-GENERATED by cli/scripts/embed-assets.ts — do not edit by hand.
// Regenerate with: npm --prefix cli run embed-assets
//
// These string constants are the source-of-truth content that
// `subwave init` materialises into SUBWAVE_HOME. CI verifies they match
// the original files at the repo root.


// docker-compose.yml
export const COMPOSE_YML = `# SUB/WAVE — production orchestration. Only Caddy binds a host port; Cloudflare
# terminates TLS in front. Image-first: services pull baked GHCR images (the
# build: blocks let a checkout rebuild locally). State persists in <repo>/state
# (override with STATE_DIR) — a bind mount, so \`down -v\` won't touch it, but
# keep it clear of \`git clean -dffx\`.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave
# Optional host relocation for the stem cache (STEMS_DIR in .env). The
# container path is fixed because compose cannot know which station is active;
# SUBWAVE_STEMS_DIR hands that path to the controller and the broadcast
# entrypoint, which re-append the per-station segment under it. Unset leaves
# the cache under the state dir, exactly as before.
x-stems: &stems-mount \${STEMS_DIR:-\${STATE_DIR:-./state}/stems}:/var/sub-wave/stems

# Cap container log growth (10m × 3 ≈ 30MB/service) — the default json-file
# driver is unbounded and eventually fills the host disk.
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  # -------------------------------------------------------------------------
  # CADDY — public edge, the only service bound to a host port
  # -------------------------------------------------------------------------
  caddy:
    image: ghcr.io/perminder-klair/subwave-caddy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.caddy
    container_name: sub-wave-caddy
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      # web has no healthcheck (static Next.js server) — started is enough.
      # Gate the edge on controller + broadcast health to avoid cold-boot 502s.
      web:
        condition: service_started
      controller:
        condition: service_healthy
      broadcast:
        condition: service_healthy
    ports:
      - "\${CADDY_PORT:-7700}:80"
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  # -------------------------------------------------------------------------
  # BROADCAST — icecast2 + liquidsoap in one container
  # -------------------------------------------------------------------------
  # The entrypoint resolves ICECAST_* passwords, renders icecast.xml, and
  # launches both; if either dies the container exits and restarts the pair.
  broadcast:
    image: ghcr.io/perminder-klair/subwave-broadcast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcast
    container_name: sub-wave-broadcast
    restart: unless-stopped
    logging: *default-logging
    environment:
      # Optional — blank means random values generated on first boot and
      # persisted to state/icecast-secrets.env (delete that file + restart
      # broadcast to rotate).
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
      # Concurrent-listener ceiling (<limits><clients>). Empty → 100.
      - ICECAST_MAX_CLIENTS=\${ICECAST_MAX_CLIENTS:-}
      # Proxies whose X-Forwarded-For icecast should believe (real listener IPs
      # in admin → Listeners). Unset resolves the bundled \`caddy\` by name at
      # render time — lands on every restart but misses the very first cold
      # boot (caddy waits on this service's healthcheck). Pin an IP here for
      # first-boot accuracy.
      - ICECAST_TRUSTED_PROXY_IPS=\${ICECAST_TRUSTED_PROXY_IPS:-}
      - ICECAST_TRUSTED_PROXY_HOSTS=\${ICECAST_TRUSTED_PROXY_HOSTS:-}
      # Keeps the hourly archive paths (%Y-%m-%d/%H-00.mp3) on local wall time.
      - TZ=\${TZ:-Europe/London}
      # Container path of the STEMS_DIR bind mount above — empty when the
      # operator did not relocate, which keeps the cache under the state dir
      # exactly as before. Named apart from STEMS_DIR on purpose: that one is a
      # HOST path and reaches the controller through \`env_file: ./.env\`.
      - SUBWAVE_STEMS_DIR=\${STEMS_DIR:+/var/sub-wave/stems}
    extra_hosts:
      # Liquidsoap fetching Subsonic URLs that point at host services
      # (e.g. NAVIDROME_URL=http://host.docker.internal:4533).
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - *stems-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7702/status-json.xsl > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s

  # -------------------------------------------------------------------------
  # CONTROLLER — AI DJ brain
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
      args:
        # Version reported by the controller; unset → controller/package.json.
        - SUBWAVE_BUILD_VERSION=\${SUBWAVE_BUILD_VERSION:-}
    container_name: sub-wave-controller
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      broadcast:
        condition: service_healthy
      # So a selective \`up -d controller\` also brings the socket-proxy up.
      # Remove this entry too if you drop the proxy below.
      docker-socket-proxy:
        condition: service_started
    environment:
      # Enables the production-only admin gate (refuses to boot without
      # ADMIN_USER + ADMIN_PASS).
      - NODE_ENV=production
      # Schedule slots are day-of-week + hour via date.getHours(); without TZ
      # the container runs UTC and fires shows an hour early during BST.
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
      # Container path of the STEMS_DIR bind mount above — empty when the
      # operator did not relocate, which keeps the cache under the state dir
      # exactly as before. Named apart from STEMS_DIR on purpose: that one is a
      # HOST path and reaches the controller through \`env_file: ./.env\`.
      - SUBWAVE_STEMS_DIR=\${STEMS_DIR:+/var/sub-wave/stems}
      # Optional Chatterbox/PocketTTS sidecar (--profile tts-heavy). When the
      # profile is off the URL is unreachable and TTS falls back to Piper.
      - TTS_HEAVY_URL=\${TTS_HEAVY_URL:-http://tts-heavy:8080}
      # Acoustic-analysis sidecar (default-on below). Probed first, then a
      # local venv; falls through to NULL analysis. See music/analyzer.ts.
      - ANALYZE_URL=\${ANALYZE_URL:-http://analyzer:8080}
      # Per-container stats for the admin Stats panel, via the socket-proxy —
      # the controller never touches the raw Docker socket. Unset to disable.
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    env_file:
      # All controller config (Navidrome creds, LLM keys, ADMIN_*, …). Unset
      # vars are simply absent — settings.json covers what the wizard manages.
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - *stems-mount
      # Optional, for "Never Play Again"'s Navidrome-wide exclusion (see
      # NEVER_PLAY_LIBRARY_PATH in .env.example) — mount your Navidrome
      # music-library root here, READ-WRITE, pointed at the SAME directory
      # Navidrome itself scans. Uncomment and set HOST_MUSIC_PATH in .env,
      # then set NEVER_PLAY_LIBRARY_PATH=/music to match. Leave both unset
      # and the feature still works — "Never Play Again" still permanently
      # blocks a track inside SUB/WAVE and skips it immediately either way;
      # this mount only extends that to Navidrome's own catalog too.
      # - \${HOST_MUSIC_PATH}:/music
    # curl is in the controller image; /health is served at the router root.
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7701/health > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  # -------------------------------------------------------------------------
  # DOCKER-SOCKET-PROXY — locked-down Docker API for the Stats system panel
  # -------------------------------------------------------------------------
  # Owns the real /var/run/docker.sock and exposes a read-only, GET-only,
  # CONTAINERS-section-only slice over internal TCP. Optional: remove it (plus
  # the controller's DOCKER_HOST + depends_on entry) to drop the Stats panel.
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    container_name: sub-wave-docker-proxy
    restart: unless-stopped
    logging: *default-logging
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # -------------------------------------------------------------------------
  # WEB — Next.js listener UI
  # -------------------------------------------------------------------------
  web:
    image: ghcr.io/perminder-klair/subwave-web:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        # Source builds only — absolute URLs render off the RUNTIME env below.
        - SITE_URL=\${SITE_URL:-}
        # NEXT_PUBLIC_* is inlined into the client bundle at BUILD time.
        - NEXT_PUBLIC_GA_ID=\${NEXT_PUBLIC_GA_ID:-}
        # Admin footer version; unset → web/package.json (web/next.config.js).
        - SUBWAVE_BUILD_VERSION=\${SUBWAVE_BUILD_VERSION:-}
    container_name: sub-wave-web
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      # The homepage renders per-request against the controller — starting web
      # before it is healthy serves broken first pages.
      controller:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - SUBWAVE_HOMEPAGE=\${SUBWAVE_HOMEPAGE:-player}
      - SUBWAVE_DJ_BRAIN_ENABLED=\${SUBWAVE_DJ_BRAIN_ENABLED:-false}
      # RUNTIME source of truth for absolute URLs (canonicals, og:url,
      # robots.txt, sitemap.xml) — the generic image serves any domain.
      - SITE_URL=\${SITE_URL:-}
      # Set to 1 to keep the shared product pages (landing, docs, news,
      # catalogs) self-canonical + in this install's sitemap instead of
      # crediting getsubwave.com (web/lib/site.ts IS_OFFICIAL_SITE).
      - SUBWAVE_INDEX_ALL=\${SUBWAVE_INDEX_ALL:-}
      # GA Measurement ID at RUNTIME (web/lib/ga.ts) — analytics turn on with a
      # \`web\` recreate, no rebuild. The build-arg above still bakes it.
      - GA_ID=\${NEXT_PUBLIC_GA_ID:-}
      # Server-side base URL for generateMetadata; internal compose name, not
      # exposed to the browser (which uses /api via Caddy).
      - CONTROLLER_INTERNAL_URL=http://controller:7701

  # -------------------------------------------------------------------------
  # TTS-HEAVY (optional) — sidecar for Chatterbox + PocketTTS
  # -------------------------------------------------------------------------
  # Heavy PyTorch engines kept out of the controller image (#103). NOT started
  # by default: \`docker compose --profile tts-heavy up -d\`. With the profile
  # off, TTS_HEAVY_URL is unreachable and the dispatcher falls back to Piper.
  tts-heavy:
    image: ghcr.io/perminder-klair/subwave-tts-heavy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.tts-heavy
      args:
        # GPU opt-in (source build only): point at a CUDA wheel index and layer
        # on docker-compose.tts-heavy-gpu.yml. See docs/gpu-tts.md.
        CHATTERBOX_TORCH_INDEX_URL: \${CHATTERBOX_TORCH_INDEX_URL:-https://download.pytorch.org/whl/cpu}
        # RTX 50-series only: override chatterbox's torch==2.6.0 pin (no sm_120
        # kernels), e.g. CHATTERBOX_TORCH_SPEC="torch==2.9.1 torchaudio==2.9.1".
        CHATTERBOX_TORCH_SPEC: \${CHATTERBOX_TORCH_SPEC:-}
    # amd64-only image; pinned so it runs under emulation on arm64 hosts.
    platform: linux/amd64
    container_name: sub-wave-tts-heavy
    restart: unless-stopped
    logging: *default-logging
    # OOM containment: a runaway model load dies here instead of triggering the
    # host OOM-killer and taking broadcast/controller down. Default is generous.
    mem_limit: \${TTS_HEAVY_MEM_LIMIT:-10g}
    profiles: ["tts-heavy"]
    environment:
      # 'cpu' or 'cuda'; the server falls back to cpu when CUDA is absent.
      - TTS_HEAVY_DEVICE=\${TTS_HEAVY_DEVICE:-cpu}
      # Default PocketTTS voice when a persona doesn't override it.
      - POCKET_TTS_VOICE=\${POCKET_TTS_VOICE:-alba}
      # Which engines to load (comma-separated). Each costs RAM + a first-boot
      # weight download; set a single engine if you only use one.
      - TTS_HEAVY_ENGINES=\${TTS_HEAVY_ENGINES:-chatterbox,pocket-tts}
      # Idle seconds before an engine's worker is stopped and its memory
      # returned (0 = always resident). Empty picks the device-aware default:
      # 1800 on cuda, 3600 on cpu. Reloads on the next spoken line, or ahead of
      # one when the idle pause releases (#1579). Per-engine overrides:
      # CHATTERBOX_IDLE_UNLOAD_S / POCKET_TTS_IDLE_UNLOAD_S.
      - TTS_HEAVY_IDLE_UNLOAD_S=\${TTS_HEAVY_IDLE_UNLOAD_S:-}
      - CHATTERBOX_IDLE_UNLOAD_S=\${CHATTERBOX_IDLE_UNLOAD_S:-}
      - POCKET_TTS_IDLE_UNLOAD_S=\${POCKET_TTS_IDLE_UNLOAD_S:-}
      # Seconds /speak waits for a cold engine to load before giving up and
      # letting the DJ fall through to its rescue voice.
      - TTS_HEAVY_LOAD_TIMEOUT_S=\${TTS_HEAVY_LOAD_TIMEOUT_S:-}
      # Fallback Chatterbox reference WAV for zero-shot cloning: used only when
      # a spoken line arrives with no persona voice of its own. A path INSIDE
      # this container — /var/sub-wave is the shared state mount, so
      # /var/sub-wave/voices/<file>.wav is the one that resolves on both sides.
      # The local (AIO) chatterbox path already honoured this; forwarding it
      # here is what makes the sidecar agree (#1591).
      - CHATTERBOX_REFERENCE_WAV=\${CHATTERBOX_REFERENCE_WAV:-}
      # Optional — PocketTTS voice CLONING (#238): the cloning weights are
      # gated on HF; accept the terms at huggingface.co/kyutai/pocket-tts and
      # set HF_TOKEN. Without it, cloned .wav voices revert to a built-in.
      - HF_TOKEN=\${HF_TOKEN:-}
    volumes:
      # Shared with the controller — WAVs land in /var/sub-wave/voice/*.
      - *state-mount
      # Persist HF caches across recreates, or the multi-GB boot-time weight
      # fetch repeats on every pull/rebuild.
      - tts-heavy-chatterbox-cache:/opt/chatterbox/hf-cache
      - tts-heavy-pocket-cache:/opt/pocket-tts/hf-cache

  # -------------------------------------------------------------------------
  # ANALYZER — acoustic-analysis sidecar (bpm/key/intro/loudness; optional
  # CLAP "sounds-like" embeddings + Demucs vocal ranges)
  # -------------------------------------------------------------------------
  # Starts by default (only the tts-heavy voices stay opt-in).
  # Off switch: ANALYZER_REPLICAS=0 in .env removes the container (the next
  # \`up -d\` stops and deletes it) — for operators who run analysis elsewhere via
  # ANALYZE_URL and don't want a redundant idle image. Unset/empty = 1 = the
  # default-on station, unchanged. A PROFILE can't express this: profiles are
  # opt-in only, and an empty interpolated profile drops the service for anyone
  # who sets COMPOSE_PROFILES at all (which docs/tts-heavy.md tells Unraid and
  # Portainer operators to do). See docs/tts-heavy.md#turning-the-analyzer-off.
  analyzer:
    # Default: LEAN multi-arch image. ANALYZER_HEAVY=1 in .env switches to the
    # CLAP + Demucs \`subwave-analyzer-heavy\` image (amd64-only; on arm64 also
    # set DOCKER_DEFAULT_PLATFORM=linux/amd64 to run emulated).
    image: ghcr.io/perminder-klair/subwave-analyzer\${ANALYZER_HEAVY:+-heavy}:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.analyzer
      args:
        # Local build mirrors the pulled image: lean unless ANALYZER_HEAVY set.
        WITH_CLAP: \${ANALYZER_HEAVY:+1}
        WITH_DEMUCS: \${ANALYZER_HEAVY:+1}
    container_name: sub-wave-analyzer
    # 0 = don't create this container at all (see the off switch above).
    # 0 and 1 are the ONLY valid values: container_name is fixed above, and
    # compose refuses a fixed name for >1 replica, so 2 fails every command.
    deploy:
      replicas: \${ANALYZER_REPLICAS:-1}
    restart: unless-stopped
    logging: *default-logging
    # OOM containment: a runaway analysis dies here instead of triggering the
    # host OOM-killer and taking broadcast/controller down. Default is generous.
    mem_limit: \${ANALYZER_MEM_LIMIT:-6g}
    environment:
      # Force CLAP / Demucs on for the whole pass. Usually unnecessary — the
      # admin toggles drive these per request.
      - ANALYZE_AUDIO_EMBEDDING=\${ANALYZE_AUDIO_EMBEDDING:-}
      - ANALYZE_VOCAL_ACTIVITY=\${ANALYZE_VOCAL_ACTIVITY:-}
      # Torch device for CLAP/Demucs: auto (default) / cpu / cuda. Only
      # meaningful on the cuda flavour; cpu-wheel images resolve to cpu.
      - ANALYZE_DEVICE=\${ANALYZE_DEVICE:-}
      # Idle seconds before the worker drops CLAP/Demucs models (0 = never).
      # Default 300 on cuda (frees VRAM), 1800 on cpu — otherwise one backfill
      # parks ~GBs in swap on a small host (#1204).
      - ANALYZE_IDLE_UNLOAD_S=\${ANALYZE_IDLE_UNLOAD_S:-}
      # Idle seconds before the sidecar recycles the whole worker process —
      # reclaims the ~1GB of scratch a model release can't return (default
      # 3600; 0 = never). Requests racing a recycle queue behind the respawn.
      - ANALYZE_RECYCLE_IDLE_S=\${ANALYZE_RECYCLE_IDLE_S:-}
      - CLAP_MODEL=\${CLAP_MODEL:-}
      - CLAP_MODEL_PATH=\${CLAP_MODEL_PATH:-}
      # Demucs model + analysis-window overrides (see .env.example).
      - DEMUCS_MODEL=\${DEMUCS_MODEL:-}
      - ANALYZE_SECONDS=\${ANALYZE_SECONDS:-}
      - ANALYZE_CONCURRENCY=\${ANALYZE_CONCURRENCY:-}
      - ANALYZE_CLAP_WINDOWS=\${ANALYZE_CLAP_WINDOWS:-}
      - ANALYZE_OUTRO_SECONDS=\${ANALYZE_OUTRO_SECONDS:-}
      # CLAP isn't gated, but anonymous HF downloads are rate-limited. Same var
      # as tts-heavy — set once and both sidecars pick it up.
      - HF_TOKEN=\${HF_TOKEN:-}
    volumes:
      # Shared mount — reads tracks pre-fetched into /var/sub-wave/analyze-tmp.
      - *state-mount
      - *stems-mount
      # Persist the CLAP/Demucs HF cache across recreates.
      - analyzer-cache:/opt/analyzer/hf-cache

volumes:
  caddy-data:
  caddy-config:
  tts-heavy-chatterbox-cache:
  tts-heavy-pocket-cache:
  analyzer-cache:
`;

// docker-compose.byo.yml
export const COMPOSE_BYO_YML = `# SUB/WAVE — production without the bundled reverse proxy. Use this when you
# already run Traefik/nginx/Caddy: web, controller, and broadcast bind host
# ports (\${WEB_PORT:-7700} / \${CONTROLLER_PORT:-7701} / \${ICECAST_PORT:-7702})
# and your proxy fronts them. Liquidsoap stays internal to the broadcast
# container.
#
# Ports bind 0.0.0.0 by default; if your proxy runs on THIS host, set
# BIND_ADDRESS=127.0.0.1 in .env so the services are only reachable on loopback.
#
# The web image is baked for same-origin /api + /stream.mp3, so point your proxy
# at ONE hostname and replicate docker/Caddyfile's route table:
#   /api/listener-auth → 404 / deny         (do this one FIRST — see below)
#   /stream*                 → host:\${ICECAST_PORT}      (keep path; disable buffering)
#   /listen.pls /listen.m3u  → host:\${CONTROLLER_PORT}   (keep path)
#   /api/*                   → host:\${CONTROLLER_PORT}   (strip the /api prefix)
#   everything               → host:\${WEB_PORT}
# Split hostnames need a web rebuild with NEXT_PUBLIC_API_URL /
# NEXT_PUBLIC_STREAM_URL (baked at build time).
#
# Block /api/listener-auth at your proxy: it is Icecast's URL-auth callback and
# answers 200/401 on the shared privacy.password, so routing it hands the
# internet a password oracle (#478). Icecast reaches the controller directly
# over the compose network and never needs it through the proxy.
#
# State persists in <repo>/state (override with STATE_DIR); bind mount, so
# \`docker compose down -v\` won't touch it.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave
# Optional host relocation for the stem cache (STEMS_DIR in .env). The
# container path is fixed because compose cannot know which station is active;
# SUBWAVE_STEMS_DIR hands that path to the controller and the broadcast
# entrypoint, which re-append the per-station segment under it. Unset leaves
# the cache under the state dir, exactly as before.
x-stems: &stems-mount \${STEMS_DIR:-\${STATE_DIR:-./state}/stems}:/var/sub-wave/stems

# Cap container log growth (10m × 3 ≈ 30MB/service).
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  # -------------------------------------------------------------------------
  # BROADCAST — icecast2 + liquidsoap in one container
  # -------------------------------------------------------------------------
  broadcast:
    image: ghcr.io/perminder-klair/subwave-broadcast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcast
    container_name: sub-wave-broadcast
    restart: unless-stopped
    logging: *default-logging
    environment:
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
      # Concurrent-listener ceiling (<limits><clients>). Empty → 100.
      - ICECAST_MAX_CLIENTS=\${ICECAST_MAX_CLIENTS:-}
      # No bundled edge here, so nothing resolves by default and listener rows
      # show your proxy's address. Set this to that proxy's IP (as icecast sees
      # it) for real listener IPs in admin → Listeners. See docs/deployment.md.
      - ICECAST_TRUSTED_PROXY_IPS=\${ICECAST_TRUSTED_PROXY_IPS:-}
      - ICECAST_TRUSTED_PROXY_HOSTS=\${ICECAST_TRUSTED_PROXY_HOSTS:-}
      - TZ=\${TZ:-Europe/London}
      # Container path of the STEMS_DIR bind mount above — empty when the
      # operator did not relocate, which keeps the cache under the state dir
      # exactly as before. Named apart from STEMS_DIR on purpose: that one is a
      # HOST path and reaches the controller through \`env_file: ./.env\`.
      - SUBWAVE_STEMS_DIR=\${STEMS_DIR:+/var/sub-wave/stems}
    ports:
      - "\${BIND_ADDRESS:-0.0.0.0}:\${ICECAST_PORT:-7702}:7702"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - *stems-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7702/status-json.xsl > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s

  # -------------------------------------------------------------------------
  # CONTROLLER — AI DJ brain, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
      args:
        # Version reported by the controller; unset → controller/package.json.
        - SUBWAVE_BUILD_VERSION=\${SUBWAVE_BUILD_VERSION:-}
    container_name: sub-wave-controller
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      broadcast:
        condition: service_healthy
      # So a selective \`up -d controller\` also brings the socket-proxy up.
      # Remove this entry too if you drop the proxy below.
      docker-socket-proxy:
        condition: service_started
    environment:
      - NODE_ENV=production
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
      # Container path of the STEMS_DIR bind mount above — empty when the
      # operator did not relocate, which keeps the cache under the state dir
      # exactly as before. Named apart from STEMS_DIR on purpose: that one is a
      # HOST path and reaches the controller through \`env_file: ./.env\`.
      - SUBWAVE_STEMS_DIR=\${STEMS_DIR:+/var/sub-wave/stems}
      # Optional Chatterbox/PocketTTS sidecar (--profile tts-heavy);
      # unreachable URL → fall back to Piper.
      - TTS_HEAVY_URL=\${TTS_HEAVY_URL:-http://tts-heavy:8080}
      # Acoustic-analysis sidecar (default-on below). Probed, then local venv.
      - ANALYZE_URL=\${ANALYZE_URL:-http://analyzer:8080}
      # Admin Stats panel via the socket-proxy — the controller never touches
      # the raw Docker socket. Unset to disable.
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      # BIND_ADDRESS=127.0.0.1 keeps the admin API off the network when the
      # proxy is same-host (see header).
      - "\${BIND_ADDRESS:-0.0.0.0}:\${CONTROLLER_PORT:-7701}:7701"
    volumes:
      - *state-mount
      - *stems-mount
      # Optional, for "Never Play Again"'s Navidrome-wide exclusion (see
      # NEVER_PLAY_LIBRARY_PATH in .env.example) — same guidance as the
      # default docker-compose.yml's controller service.
      # - \${HOST_MUSIC_PATH}:/music
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7701/health > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  # -------------------------------------------------------------------------
  # DOCKER-SOCKET-PROXY — locked-down Docker API for the Stats system panel
  # -------------------------------------------------------------------------
  # Read-only, GET-only, CONTAINERS-section-only slice of the Docker API over
  # internal TCP. Optional: remove it (plus the controller's DOCKER_HOST +
  # depends_on entry) to drop the Stats panel.
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    container_name: sub-wave-docker-proxy
    restart: unless-stopped
    logging: *default-logging
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # -------------------------------------------------------------------------
  # WEB — Next.js listener UI, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  web:
    image: ghcr.io/perminder-klair/subwave-web:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - SITE_URL=\${SITE_URL:-}
        - NEXT_PUBLIC_GA_ID=\${NEXT_PUBLIC_GA_ID:-}
        # Admin footer version; unset → web/package.json (web/next.config.js).
        - SUBWAVE_BUILD_VERSION=\${SUBWAVE_BUILD_VERSION:-}
    container_name: sub-wave-web
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      # The homepage renders per-request against the controller — starting web
      # before it is healthy serves broken first pages.
      controller:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - SUBWAVE_HOMEPAGE=\${SUBWAVE_HOMEPAGE:-player}
      - SUBWAVE_DJ_BRAIN_ENABLED=\${SUBWAVE_DJ_BRAIN_ENABLED:-false}
      - SITE_URL=\${SITE_URL:-}
      # Set to 1 to keep the shared product pages (landing, docs, news,
      # catalogs) self-canonical + in this install's sitemap instead of
      # crediting getsubwave.com (web/lib/site.ts IS_OFFICIAL_SITE).
      - SUBWAVE_INDEX_ALL=\${SUBWAVE_INDEX_ALL:-}
      # GA Measurement ID at RUNTIME (web/lib/ga.ts) — analytics turn on with a
      # \`web\` recreate, no rebuild.
      - GA_ID=\${NEXT_PUBLIC_GA_ID:-}
      # Server-side base URL for generateMetadata; internal compose name.
      - CONTROLLER_INTERNAL_URL=http://controller:7701
    ports:
      - "\${BIND_ADDRESS:-0.0.0.0}:\${WEB_PORT:-7700}:7700"

  # -------------------------------------------------------------------------
  # TTS-HEAVY (optional) — sidecar for Chatterbox + PocketTTS
  # -------------------------------------------------------------------------
  # NOT started by default (#103):
  #   docker compose -f docker-compose.byo.yml --profile tts-heavy up -d
  # With the profile off, the controller falls back to Piper.
  tts-heavy:
    image: ghcr.io/perminder-klair/subwave-tts-heavy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.tts-heavy
      args:
        # GPU opt-in (source build only) — see docs/gpu-tts.md.
        CHATTERBOX_TORCH_INDEX_URL: \${CHATTERBOX_TORCH_INDEX_URL:-https://download.pytorch.org/whl/cpu}
        # RTX 50-series only: override chatterbox's torch==2.6.0 pin.
        CHATTERBOX_TORCH_SPEC: \${CHATTERBOX_TORCH_SPEC:-}
    # amd64-only image; pinned so it runs under emulation on arm64 hosts.
    platform: linux/amd64
    container_name: sub-wave-tts-heavy
    restart: unless-stopped
    logging: *default-logging
    # OOM containment: a runaway model load dies here, not via the host
    # OOM-killer taking broadcast/controller with it.
    mem_limit: \${TTS_HEAVY_MEM_LIMIT:-10g}
    profiles: ["tts-heavy"]
    environment:
      - TTS_HEAVY_DEVICE=\${TTS_HEAVY_DEVICE:-cpu}
      - POCKET_TTS_VOICE=\${POCKET_TTS_VOICE:-alba}
      # Which engines to load (comma-separated); each costs RAM + weights.
      - TTS_HEAVY_ENGINES=\${TTS_HEAVY_ENGINES:-chatterbox,pocket-tts}
      # Idle seconds before an engine's worker is stopped and its memory
      # returned (empty = 1800 cuda / 3600 cpu; 0 = always resident). See
      # .env.example and #1579.
      - TTS_HEAVY_IDLE_UNLOAD_S=\${TTS_HEAVY_IDLE_UNLOAD_S:-}
      - CHATTERBOX_IDLE_UNLOAD_S=\${CHATTERBOX_IDLE_UNLOAD_S:-}
      - POCKET_TTS_IDLE_UNLOAD_S=\${POCKET_TTS_IDLE_UNLOAD_S:-}
      # Seconds /speak waits for a cold engine to load before giving up and
      # letting the DJ fall through to its rescue voice.
      - TTS_HEAVY_LOAD_TIMEOUT_S=\${TTS_HEAVY_LOAD_TIMEOUT_S:-}
      # Fallback Chatterbox reference WAV when a line has no persona voice of
      # its own — a path inside this container (see docker-compose.yml).
      - CHATTERBOX_REFERENCE_WAV=\${CHATTERBOX_REFERENCE_WAV:-}
      # Optional — PocketTTS voice cloning (#238): accept the terms at
      # huggingface.co/kyutai/pocket-tts and set HF_TOKEN.
      - HF_TOKEN=\${HF_TOKEN:-}
    volumes:
      - *state-mount
      # Persist HF caches across recreates, or the multi-GB weight fetch
      # repeats every time.
      - tts-heavy-chatterbox-cache:/opt/chatterbox/hf-cache
      - tts-heavy-pocket-cache:/opt/pocket-tts/hf-cache

  # -------------------------------------------------------------------------
  # ANALYZER — acoustic-analysis sidecar (bpm/key/intro/loudness; optional
  # CLAP "sounds-like" embeddings + Demucs vocal ranges)
  # -------------------------------------------------------------------------
  # Starts by default; only the tts-heavy voices stay opt-in.
  # Off switch: ANALYZER_REPLICAS=0 in .env removes the container (the next
  # \`up -d\` stops and deletes it) — for operators who run analysis elsewhere via
  # ANALYZE_URL and don't want a redundant idle image. Unset/empty = 1 = the
  # default-on station, unchanged. A PROFILE can't express this: profiles are
  # opt-in only, and an empty interpolated profile drops the service for anyone
  # who sets COMPOSE_PROFILES at all (which docs/tts-heavy.md tells Unraid and
  # Portainer operators to do). See docs/tts-heavy.md#turning-the-analyzer-off.
  analyzer:
    # Default: LEAN multi-arch. ANALYZER_HEAVY=1 in .env → CLAP + Demucs heavy
    # image (amd64-only; on arm64 also set DOCKER_DEFAULT_PLATFORM=linux/amd64).
    image: ghcr.io/perminder-klair/subwave-analyzer\${ANALYZER_HEAVY:+-heavy}:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.analyzer
      args:
        # Local build mirrors the pulled image: lean unless ANALYZER_HEAVY set.
        WITH_CLAP: \${ANALYZER_HEAVY:+1}
        WITH_DEMUCS: \${ANALYZER_HEAVY:+1}
    container_name: sub-wave-analyzer
    # 0 = don't create this container at all (see the off switch above).
    # 0 and 1 are the ONLY valid values: container_name is fixed above, and
    # compose refuses a fixed name for >1 replica, so 2 fails every command.
    deploy:
      replicas: \${ANALYZER_REPLICAS:-1}
    restart: unless-stopped
    logging: *default-logging
    # OOM containment: a runaway analysis dies here, not via the host
    # OOM-killer taking broadcast/controller with it.
    mem_limit: \${ANALYZER_MEM_LIMIT:-6g}
    environment:
      # Force CLAP / Demucs on for the whole pass; usually the admin toggles
      # drive these per request.
      - ANALYZE_AUDIO_EMBEDDING=\${ANALYZE_AUDIO_EMBEDDING:-}
      - ANALYZE_VOCAL_ACTIVITY=\${ANALYZE_VOCAL_ACTIVITY:-}
      # Torch device for CLAP/Demucs: auto (default) / cpu / cuda.
      - ANALYZE_DEVICE=\${ANALYZE_DEVICE:-}
      # Idle seconds before the worker drops CLAP/Demucs models (0 = never;
      # default 300 cuda / 1800 cpu — see #1204).
      - ANALYZE_IDLE_UNLOAD_S=\${ANALYZE_IDLE_UNLOAD_S:-}
      # Idle seconds before the sidecar recycles the whole worker process
      # (default 3600; 0 = never).
      - ANALYZE_RECYCLE_IDLE_S=\${ANALYZE_RECYCLE_IDLE_S:-}
      - CLAP_MODEL=\${CLAP_MODEL:-}
      - CLAP_MODEL_PATH=\${CLAP_MODEL_PATH:-}
      # Demucs model + analysis-window overrides (see .env.example).
      - DEMUCS_MODEL=\${DEMUCS_MODEL:-}
      - ANALYZE_SECONDS=\${ANALYZE_SECONDS:-}
      - ANALYZE_CONCURRENCY=\${ANALYZE_CONCURRENCY:-}
      - ANALYZE_CLAP_WINDOWS=\${ANALYZE_CLAP_WINDOWS:-}
      - ANALYZE_OUTRO_SECONDS=\${ANALYZE_OUTRO_SECONDS:-}
      # Anonymous HF downloads are rate-limited; same var as tts-heavy.
      - HF_TOKEN=\${HF_TOKEN:-}
    volumes:
      - *state-mount
      - *stems-mount
      - analyzer-cache:/opt/analyzer/hf-cache

volumes:
  tts-heavy-chatterbox-cache:
  tts-heavy-pocket-cache:
  analyzer-cache:
`;

// docker-compose.dev.yml
export const COMPOSE_DEV_YML = `# SUB/WAVE — dev compose (local smoke test): Broadcast + Controller only.
# The Next.js UI runs separately via \`cd web && npm run dev\` for hot reload.
# State + sounds + radio.liq are bind-mounted so dev cycles need no rebuilds.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave
# Optional host relocation for the stem cache (STEMS_DIR in .env). The
# container path is fixed because compose cannot know which station is active;
# SUBWAVE_STEMS_DIR hands that path to the controller and the broadcast
# entrypoint, which re-append the per-station segment under it. Unset leaves
# the cache under the state dir, exactly as before.
x-stems: &stems-mount \${STEMS_DIR:-\${STATE_DIR:-./state}/stems}:/var/sub-wave/stems

# Cap container log growth (10m × 3 ≈ 30MB/service).
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  # -------------------------------------------------------------------------
  # BROADCAST — icecast2 + liquidsoap in one container
  # -------------------------------------------------------------------------
  # Icecast exposed on :7702 for direct dev access; liquidsoap stays internal.
  broadcast:
    image: ghcr.io/perminder-klair/subwave-broadcast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcast
    # No \`platform:\` pin. On Apple Silicon, forcing linux/amd64 routes
    # liquidsoap through emulation where clock_nanosleep fails
    # (\`Unix.Unix_error(EUNKNOWNERR 0)\`) — the clock loop dies on every boot
    # and Icecast gets no source. The base is multi-arch; build natively.
    container_name: sub-wave-broadcast
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "7702:7702"
    environment:
      # Optional — blank means random values generated on first boot and
      # persisted to state/icecast-secrets.env.
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
      # Concurrent-listener ceiling (<limits><clients>). Empty → 100.
      - ICECAST_MAX_CLIENTS=\${ICECAST_MAX_CLIENTS:-}
      # Dev has no edge in front of icecast, so these stay empty and listener
      # rows already show the real peer.
      - ICECAST_TRUSTED_PROXY_IPS=\${ICECAST_TRUSTED_PROXY_IPS:-}
      - ICECAST_TRUSTED_PROXY_HOSTS=\${ICECAST_TRUSTED_PROXY_HOSTS:-}
      - TZ=\${TZ:-Europe/London}
      # Container path of the STEMS_DIR bind mount above — empty when the
      # operator did not relocate, which keeps the cache under the state dir
      # exactly as before. Named apart from STEMS_DIR on purpose: that one is a
      # HOST path and reaches the controller through \`env_file: ./.env\`.
      - SUBWAVE_STEMS_DIR=\${STEMS_DIR:+/var/sub-wave/stems}
    extra_hosts:
      # Liquidsoap fetching Subsonic URLs that point at host services.
      - "host.docker.internal:host-gateway"
    volumes:
      # Bind-mounts override the baked-in copies — radio.liq edits and new
      # sounds land on the next restart, no rebuild.
      - ./liquidsoap/radio.liq:/etc/liquidsoap/radio.liq:ro
      - ./sounds:/sounds:ro
      - *state-mount
      - *stems-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7702/status-json.xsl > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s

  # -------------------------------------------------------------------------
  # CONTROLLER — the AI DJ brain
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
      args:
        # Version reported by the controller; unset → controller/package.json.
        # The dev web UI resolves its own via \`git describe\` (next.config.js).
        - SUBWAVE_BUILD_VERSION=\${SUBWAVE_BUILD_VERSION:-}
    platform: linux/amd64
    container_name: sub-wave-controller
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      broadcast:
        condition: service_healthy
      # So a selective \`up -d controller\` also brings the socket-proxy up.
      # Remove this entry too if you drop the proxy below.
      docker-socket-proxy:
        condition: service_started
    environment:
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
      # Container path of the STEMS_DIR bind mount above — empty when the
      # operator did not relocate, which keeps the cache under the state dir
      # exactly as before. Named apart from STEMS_DIR on purpose: that one is a
      # HOST path and reaches the controller through \`env_file: ./.env\`.
      - SUBWAVE_STEMS_DIR=\${STEMS_DIR:+/var/sub-wave/stems}
      # Optional Chatterbox/PocketTTS sidecar (--profile tts-heavy);
      # unreachable URL → fall back to Piper.
      - TTS_HEAVY_URL=\${TTS_HEAVY_URL:-http://tts-heavy:8080}
      # Acoustic-analysis sidecar (default-on below). Probed, then local venv.
      - ANALYZE_URL=\${ANALYZE_URL:-http://analyzer:8080}
      # Admin Stats panel via the socket-proxy — the controller never touches
      # the raw Docker socket. Unset to disable.
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    ports:
      - "7701:7701"
    env_file:
      # All controller config (Navidrome creds, LLM keys, ADMIN_*, …). Unset
      # vars are simply absent — settings.json covers what the wizard manages.
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Dev runs \`tsx watch\` against bind-mounted source so controller/src/**
    # edits restart in-place. Prod uses the image's default CMD (no watch).
    command: ["node_modules/.bin/tsx", "watch", "src/server.ts"]
    volumes:
      - *state-mount
      - *stems-mount
      - ./sounds:/sounds:ro
      # Mount src/ and scripts/ only — mounting the whole controller/ dir
      # would shadow /app/node_modules with the (possibly empty) host one.
      - ./controller/src:/app/src
      - ./controller/scripts:/app/scripts
    # start_period is generous: \`tsx watch\` is slower to first boot.
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7701/health > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  # -------------------------------------------------------------------------
  # DOCKER-SOCKET-PROXY — locked-down Docker API for the Stats system panel
  # -------------------------------------------------------------------------
  # Read-only, GET-only, CONTAINERS-section-only slice of the Docker API over
  # internal TCP. Optional: remove it (plus the controller's DOCKER_HOST +
  # depends_on entry) to drop the Stats panel.
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    container_name: sub-wave-docker-proxy
    restart: unless-stopped
    logging: *default-logging
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # -------------------------------------------------------------------------
  # TTS-HEAVY (optional) — sidecar for Chatterbox + PocketTTS
  # -------------------------------------------------------------------------
  # NOT started by default:
  #   docker compose -f docker-compose.dev.yml --profile tts-heavy up -d
  # First boot downloads ~3-4GB of model weights.
  tts-heavy:
    image: ghcr.io/perminder-klair/subwave-tts-heavy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.tts-heavy
      args:
        # GPU opt-in (source build only) — see docs/gpu-tts.md.
        CHATTERBOX_TORCH_INDEX_URL: \${CHATTERBOX_TORCH_INDEX_URL:-https://download.pytorch.org/whl/cpu}
        # RTX 50-series only: override chatterbox's torch==2.6.0 pin.
        CHATTERBOX_TORCH_SPEC: \${CHATTERBOX_TORCH_SPEC:-}
    platform: linux/amd64
    container_name: sub-wave-tts-heavy
    restart: unless-stopped
    logging: *default-logging
    # OOM containment: a runaway model load dies here, not via the host
    # OOM-killer taking broadcast/controller with it.
    mem_limit: \${TTS_HEAVY_MEM_LIMIT:-10g}
    profiles: ["tts-heavy"]
    environment:
      - TTS_HEAVY_DEVICE=\${TTS_HEAVY_DEVICE:-cpu}
      - POCKET_TTS_VOICE=\${POCKET_TTS_VOICE:-alba}
      # Which engines to load (comma-separated); each costs RAM + weights.
      - TTS_HEAVY_ENGINES=\${TTS_HEAVY_ENGINES:-chatterbox,pocket-tts}
      # Idle seconds before an engine's worker is stopped and its memory
      # returned (empty = 1800 cuda / 3600 cpu; 0 = always resident). See
      # .env.example and #1579.
      - TTS_HEAVY_IDLE_UNLOAD_S=\${TTS_HEAVY_IDLE_UNLOAD_S:-}
      - CHATTERBOX_IDLE_UNLOAD_S=\${CHATTERBOX_IDLE_UNLOAD_S:-}
      - POCKET_TTS_IDLE_UNLOAD_S=\${POCKET_TTS_IDLE_UNLOAD_S:-}
      # Seconds /speak waits for a cold engine to load before giving up and
      # letting the DJ fall through to its rescue voice.
      - TTS_HEAVY_LOAD_TIMEOUT_S=\${TTS_HEAVY_LOAD_TIMEOUT_S:-}
      # Fallback Chatterbox reference WAV when a line has no persona voice of
      # its own — a path inside this container (see docker-compose.yml).
      - CHATTERBOX_REFERENCE_WAV=\${CHATTERBOX_REFERENCE_WAV:-}
      # Optional — PocketTTS voice cloning (#238); weights gated on HF.
      - HF_TOKEN=\${HF_TOKEN:-}
    volumes:
      - *state-mount
      # Persist HF caches across recreates, or the multi-GB weight fetch
      # repeats every time.
      - tts-heavy-chatterbox-cache:/opt/chatterbox/hf-cache
      - tts-heavy-pocket-cache:/opt/pocket-tts/hf-cache

  # -------------------------------------------------------------------------
  # ANALYZER — acoustic-analysis sidecar (bpm/key/intro/loudness; optional
  # CLAP "sounds-like" embeddings + Demucs vocal ranges)
  # -------------------------------------------------------------------------
  # Starts by default; only the tts-heavy voices stay opt-in.
  # Off switch: ANALYZER_REPLICAS=0 in .env removes the container (the next
  # \`up -d\` stops and deletes it) — for operators who run analysis elsewhere via
  # ANALYZE_URL and don't want a redundant idle image. Unset/empty = 1 = the
  # default-on station, unchanged. A PROFILE can't express this: profiles are
  # opt-in only, and an empty interpolated profile drops the service for anyone
  # who sets COMPOSE_PROFILES at all (which docs/tts-heavy.md tells Unraid and
  # Portainer operators to do). See docs/tts-heavy.md#turning-the-analyzer-off.
  analyzer:
    # Default: LEAN multi-arch. ANALYZER_HEAVY=1 → CLAP + Demucs heavy image.
    image: ghcr.io/perminder-klair/subwave-analyzer\${ANALYZER_HEAVY:+-heavy}:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.analyzer
      args:
        # Local build mirrors the pulled image: lean unless ANALYZER_HEAVY set.
        WITH_CLAP: \${ANALYZER_HEAVY:+1}
        WITH_DEMUCS: \${ANALYZER_HEAVY:+1}
    container_name: sub-wave-analyzer
    # 0 = don't create this container at all (see the off switch above).
    # 0 and 1 are the ONLY valid values: container_name is fixed above, and
    # compose refuses a fixed name for >1 replica, so 2 fails every command.
    deploy:
      replicas: \${ANALYZER_REPLICAS:-1}
    restart: unless-stopped
    logging: *default-logging
    # OOM containment: a runaway analysis dies here, not via the host
    # OOM-killer taking broadcast/controller with it.
    mem_limit: \${ANALYZER_MEM_LIMIT:-6g}
    environment:
      - ANALYZE_AUDIO_EMBEDDING=\${ANALYZE_AUDIO_EMBEDDING:-}
      - ANALYZE_VOCAL_ACTIVITY=\${ANALYZE_VOCAL_ACTIVITY:-}
      # Torch device for CLAP/Demucs: auto (default) / cpu / cuda.
      - ANALYZE_DEVICE=\${ANALYZE_DEVICE:-}
      # Idle seconds before the worker drops CLAP/Demucs models (0 = never;
      # default 300 cuda / 1800 cpu — see #1204).
      - ANALYZE_IDLE_UNLOAD_S=\${ANALYZE_IDLE_UNLOAD_S:-}
      # Idle seconds before the sidecar recycles the whole worker process
      # (default 3600; 0 = never).
      - ANALYZE_RECYCLE_IDLE_S=\${ANALYZE_RECYCLE_IDLE_S:-}
      - CLAP_MODEL=\${CLAP_MODEL:-}
      - CLAP_MODEL_PATH=\${CLAP_MODEL_PATH:-}
      # Demucs model + analysis-window overrides (see .env.example).
      - DEMUCS_MODEL=\${DEMUCS_MODEL:-}
      - ANALYZE_SECONDS=\${ANALYZE_SECONDS:-}
      - ANALYZE_CONCURRENCY=\${ANALYZE_CONCURRENCY:-}
      - ANALYZE_CLAP_WINDOWS=\${ANALYZE_CLAP_WINDOWS:-}
      - ANALYZE_OUTRO_SECONDS=\${ANALYZE_OUTRO_SECONDS:-}
      # Anonymous HF downloads are rate-limited; same var as tts-heavy.
      - HF_TOKEN=\${HF_TOKEN:-}
    volumes:
      - *state-mount
      - *stems-mount
      - analyzer-cache:/opt/analyzer/hf-cache

volumes:
  tts-heavy-chatterbox-cache:
  tts-heavy-pocket-cache:
  analyzer-cache:
`;

// docker-compose.tts-heavy-gpu.yml
export const COMPOSE_TTS_HEAVY_GPU_YML = `# GPU opt-in overlay for the tts-heavy sidecar — Chatterbox on CUDA.
# A device reservation can't live in the base compose (\`up\` errors on hosts
# without the NVIDIA runtime). This overlay adds it, switches the engine to
# cuda, and forces a local build (the published image ships CPU-only torch).
#
#   echo 'CHATTERBOX_TORCH_INDEX_URL=https://download.pytorch.org/whl/cu124' >> .env
#   docker compose -f docker-compose.yml -f docker-compose.tts-heavy-gpu.yml \\
#     --profile tts-heavy up -d --build
#   (BYO hosts: swap in docker-compose.byo.yml.)
#
# RTX 50-series (Blackwell / sm_120): chatterbox-tts pins torch==2.6.0, which
# has no sm_120 kernels — the cu124 build loads but 500s at synthesis. Use a
# cu128 index AND override the pin:
#
#   echo 'CHATTERBOX_TORCH_INDEX_URL=https://download.pytorch.org/whl/cu128' >> .env
#   echo 'CHATTERBOX_TORCH_SPEC=torch==2.9.1 torchaudio==2.9.1' >> .env
#
# Requirements: NVIDIA driver + Container Toolkit; pick the cuXXX wheel tag
# matching your driver (https://pytorch.org/get-started/locally/). Full guide:
# docs/gpu-tts.md.
services:
  tts-heavy:
    # Build the CUDA image locally instead of pulling the published CPU one.
    pull_policy: build
    environment:
      # The worker falls back to cpu if CUDA isn't actually visible.
      - TTS_HEAVY_DEVICE=cuda
    # The deploy.resources reservation is the modern (CDI) path. On hosts where
    # the NVIDIA runtime is registered in LEGACY mode it fails with "could not
    # select device driver nvidia"; there, delete the \`deploy:\` block and use:
    #
    #   runtime: nvidia
    #   environment:
    #     - TTS_HEAVY_DEVICE=cuda
    #     - NVIDIA_VISIBLE_DEVICES=all
    #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
`;

// docker-compose.analyzer-gpu.yml
export const COMPOSE_ANALYZER_GPU_YML = `# GPU opt-in overlay for the analyzer — CLAP + Demucs on CUDA (#1099).
# A device reservation can't live in the base compose (\`up\` errors on hosts
# without the NVIDIA runtime), so this overlay swaps in the published
# \`subwave-analyzer-cuda\` image and reserves the GPU. ANALYZER_HEAVY is
# irrelevant while applied — the image is overridden outright.
#
#   docker compose -f docker-compose.yml -f docker-compose.analyzer-gpu.yml up -d
#   (BYO hosts: swap in docker-compose.byo.yml.)
#
# Requirements: NVIDIA driver + Container Toolkit only (cu124 wheels vendor the
# CUDA runtime). The worker picks the device itself (ANALYZE_DEVICE=auto: cuda
# when torch sees a GPU, else cpu with a warning — a misconfigured host
# degrades, not fails). ANALYZE_DEVICE=cpu in .env forces CPU without dropping
# the overlay.
#
# After ~5 idle minutes the worker drops its models out of VRAM so a
# co-resident TTS/LLM gets the card back (ANALYZE_IDLE_UNLOAD_S tunes it;
# 0 keeps them resident). A few hundred MB of CUDA context remain until the
# container stops.
services:
  analyzer:
    image: ghcr.io/perminder-klair/subwave-analyzer-cuda:\${SUBWAVE_VERSION:-latest}
    # Local build with this overlay applied mirrors the published cuda image.
    build:
      args:
        WITH_CLAP: 1
        WITH_DEMUCS: 1
        WITH_CUDA: 1
    # The deploy.resources reservation is the modern (CDI) path. On hosts where
    # the NVIDIA runtime is registered in LEGACY mode it fails with "could not
    # select device driver nvidia"; there, delete the \`deploy:\` block and use:
    #
    #   runtime: nvidia
    #   environment:
    #     - NVIDIA_VISIBLE_DEVICES=all
    #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
`;

// .env.example
export const ENV_EXAMPLE = `# ═══════════════════════════════════════════════════════════════
#  SUB/WAVE — required configuration
# ═══════════════════════════════════════════════════════════════
#
# Just three vars are required to boot the stack. Everything else
# (Navidrome, LLM, TTS engine, DJ persona, …) is collected by the
# first-run wizard at http://<your-host>/onboarding after the stack is up.
#
# The wizard writes those to state/settings.json, which is the
# runtime source of truth. The optional overrides below are kept
# for 12-factor / CI / GitOps style deploys where env beats UI.

# Admin credentials gate the wizard + admin UI. Mandatory in prod
# (the controller refuses to boot without them when NODE_ENV=production).
ADMIN_USER=admin
ADMIN_PASS=                       # generate one: openssl rand -hex 16

# Public origin (used for absolute URLs, OG tags, manifest, sitemap).
# Example: https://radio.example.com
SITE_URL=

# ═══════════════════════════════════════════════════════════════
#  OPTIONAL — sensible defaults, uncomment to override
# ═══════════════════════════════════════════════════════════════

# Storage + locale
# STATE_DIR=./state
# Optional: place the stem cache on another disk. This HOST path is mounted
# into broadcast, controller and analyzer at a fixed container path, which the
# three of them read back as SUBWAVE_STEMS_DIR. Multi-station installs keep a
# per-station folder under it. Unset = the cache stays at <STATE_DIR>/stems.
# Moving it does NOT migrate what is already cached — \`mv\` the old contents
# across first, or the old copy just sits there unreferenced.
# STEMS_DIR=/mnt/bigdisk/subwave-stems
# TZ=Europe/London

# Web
# SUBWAVE_DJ_BRAIN_ENABLED=false   # true reveals the alpha DJ Brain admin settings
#                                  # Runtime flag; recreate the web container after changing.
# SUBWAVE_HOMEPAGE=player          # or 'landing' for the marketing host
# SUBWAVE_INDEX_ALL=1              # index the shared docs/news/catalog pages on
#                                  # THIS domain too; default points their
#                                  # canonicals at getsubwave.com so search
#                                  # engines credit one copy
# NEXT_PUBLIC_GA_ID=               # Google Analytics ID. Applied at RUNTIME
#                                  # (recreate \`web\`, no rebuild) as well as at
#                                  # build time. Unset → no analytics.

# Pin the whole stack to a specific published image tag. Every subwave-* image
# ref resolves \${SUBWAVE_VERSION:-latest}, so unset/removed follows :latest.
# The \`subwave\` CLI writes a concrete pin here at \`init\` (matching the CLI's
# release) and moves it forward on \`subwave update\`. Published tags are bare
# semver (e.g. 0.35.0 or 0.35), plus \`latest\`.
# SUBWAVE_VERSION=latest

# ───────── Ports (byo-proxy compose only) ─────────
# CADDY_PORT=7700
# WEB_PORT=7700
# CONTROLLER_PORT=7701
# ICECAST_PORT=7702
# Host interface the byo ports bind to. Defaults to 0.0.0.0 (all interfaces).
# Set to 127.0.0.1 when your reverse proxy runs on THIS host, so the admin
# API isn't reachable from the network directly.
# BIND_ADDRESS=0.0.0.0

# ───────── Icecast secrets ─────────
# Leave blank — the broadcast image auto-generates these on first boot and
# writes them to state/icecast-secrets.env. Override here only if you need
# specific passwords (e.g. broadcasting to an external relay).
# To rotate: delete state/icecast-secrets.env and restart broadcast +
# controller. (The merged container holds both icecast and liquidsoap, so
# the old three-way restart is collapsed into one bounce.)
# ICECAST_SOURCE_PASSWORD=
# ICECAST_ADMIN_PASSWORD=
# ICECAST_RELAY_PASSWORD=

# Max concurrent listeners across all mounts (icecast <limits><clients>).
# Unset → whatever admin → Settings → Danger zone → Max listeners says
# (default 100). Setting it here OVERRIDES that field, which is why the
# broadcast log names the source it used on every boot. Prefer the admin
# field unless you deploy 12-factor style; on the AIO image the field is the
# only way in, since there is no .env there at all.
# ICECAST_MAX_CLIENTS=

# ───────── Real listener IPs behind a proxy ─────────
# Icecast only ever sees the reverse proxy in front of it, so admin →
# Listeners shows that proxy's address (the 172.x rows) rather than the
# listener's, unless icecast is told which proxy to believe.
#
# Unset, the default compose resolves its bundled \`caddy\` by name each time
# the broadcast container starts. That covers the steady state but NOT the
# first cold boot (caddy can't be running yet — it waits on broadcast's
# healthcheck), so listener rows read as the proxy IP until the next restart.
#
# Set this to the proxy's address — as icecast sees it — for correctness from
# the first boot, and whenever the proxy isn't a compose service resolvable
# from the broadcast container (the byo compose, a host-network nginx). Space
# or comma separated; must be EXACT addresses, as icecast accepts a CIDR and
# then silently never matches it.
# ICECAST_TRUSTED_PROXY_IPS=172.20.0.100
#
# Names to resolve instead of hardcoding an address. Unset → \`caddy\`.
# ICECAST_TRUSTED_PROXY_HOSTS=caddy

# Trust Cloudflare's CF-Connecting-IP header as the listener's real address in
# the CONTROLLER (the separate, icecast-side setting is above). This is the
# identity every per-IP limit keys on: the request cooldown and hourly caps,
# the admin brute-force lockout, the station-password throttle, and like dedup.
#
# Leave it unset unless Cloudflare (proxied DNS or a tunnel) is the ONLY way
# traffic reaches this stack. Unset, the controller uses X-Forwarded-For, which
# the bundled Caddy only passes through for peers in its trusted_proxies list
# and otherwise replaces with the real peer — sound on its own. CF-Connecting-IP
# gets no such filtering, so trusting it when anyone can reach the origin
# directly lets a single spoofed header defeat every limit listed above.
# TRUST_CF_CONNECTING_IP=1

# Offline GeoIP database for the Stats page's listener-country rollup.
#
# Stats reads CF-IPCountry first, then whatever header you name in
# admin → Settings → Danger zone → Listener country. This is the last resort
# when neither carries an answer: an IP-to-country database in MaxMind's MMDB
# format (GeoLite2, DB-IP Lite and IP2Location LITE all fit), at a path the
# CONTROLLER container can read. Nothing is bundled — each has its own licence.
#
# Set here only if you want env to win over the admin field. Wrong path? One
# warning in the controller log and the header links carry on; nothing breaks.
# GEOIP_DB_PATH=/var/sub-wave/geoip/country.mmdb

# ───────── Overrides for the wizard's fields ─────────
# These all live in state/settings.json after the wizard runs. Set them here
# only if you want env to win (12-factor / CI / GitOps style deploys).
# NAVIDROME_URL=http://host.docker.internal:4533
# NAVIDROME_USER=
# NAVIDROME_PASS=
# Optional: play tracks straight off disk instead of streaming them over HTTP.
# Only worth setting when the controller container mounts the SAME library
# Navidrome scans. Note Navidrome's Subsonic \`path\` is built from tags, not read
# off disk, so it often disagrees with your real folder names (e.g. the API says
# "Chunga's Revenge" where the folder is "Chunga's Revenge (1970)"). Every
# mismatch falls back to streaming, so it is safe to leave on — it just does
# nothing for the tracks whose paths don't line up.
# MUSIC_LIBRARY_PATH=
#
# "Never Play Again" is the admin dashboard's block-and-skip action: it
# always permanently blocks the current track inside SUB/WAVE (it's never
# picked or requestable again) and skips it immediately, with no extra
# config needed. NEVER_PLAY_LIBRARY_PATH is OPTIONAL and extends that to
# Navidrome's own catalog too, by writing the track's library-relative path
# (as an escaped, literal gitignore-syntax line) to <this path>/.ndignore and
# triggering a Navidrome library scan — so the track also stops showing up
# in Navidrome itself and any other client pointed at it, not just SUB/WAVE.
#
# Set this to where you bind-mount your Navidrome music-library ROOT inside
# the CONTROLLER container, READ-WRITE, generic example: /music. It must be
# the exact same directory Navidrome itself is configured to scan — see the
# controller service's \`volumes:\` in docker-compose.yml for the matching
# bind-mount line. Leave it unset (the default) and Never Play Again still
# works fully on the SUB/WAVE side; Navidrome's own catalog just doesn't
# change.
#
# Deliberately separate from MUSIC_LIBRARY_PATH above: that one re-routes
# PLAYBACK and needs the BROADCAST container too. This one is read only by
# the controller, only to maintain that one ignore file.
# NEVER_PLAY_LIBRARY_PATH=
#
# The HOST-side path bind-mounted to NEVER_PLAY_LIBRARY_PATH above — used by
# the commented controller volume line in docker-compose.yml
# (\`- \${HOST_MUSIC_PATH}:/music\`). Generic example: /srv/music. Must be the
# same directory your Navidrome instance is configured to scan.
# HOST_MUSIC_PATH=
# TTS_SPEED=0.85
# AUTO_QUEUE_REFRESH_MINUTES=60
# Convenience only — seeds the News skill's feed on first boot. After that the
# file wins: edit it in /admin/skills or state/skills/news/SKILL.md (changing
# these vars won't move an already-scaffolded feed).
# NEWS_FEED_URL=http://feeds.bbci.co.uk/news/rss.xml
# NEWS_MAX_ITEMS=10

# ───────── Cloud LLM / TTS API keys ─────────
# The wizard accepts these in a form and writes them to state/secrets.env
# (which the controller sources on boot). Set here only for IaC-style provisioning.
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# GOOGLE_GENERATIVE_AI_API_KEY=
# OPENROUTER_API_KEY=
# REQUESTY_API_KEY=
# DEEPSEEK_API_KEY=
# AI_GATEWAY_API_KEY=
# ELEVENLABS_API_KEY=
# FISH_API_KEY=
# SEARCH_API_KEY=tvly-...           # Tavily or Brave Search key (optional, paid/metered)
# SearXNG: no env var. Configure base URL in admin UI → Settings → Search.
# Embedding key — only when embeddings use a different provider/key than chat
# (e.g. OpenRouter for embeddings, a local proxy for chat). Blank → inherit the
# chat key. OpenRouter embeddings also fall back to OPENROUTER_API_KEY above.
# EMBEDDING_API_KEY=

# ───────── Scrobbling (optional — also configurable in admin UI) ─────────
# LISTENBRAINZ_USER_TOKEN=          # ListenBrainz or LB-compatible scrobbler token
# LISTENBRAINZ_API_URL=             # optional full submit-listens URL override
#                                   # e.g. http://koito:4110/apis/listenbrainz/1/submit-listens
#                                   # otherwise set base URL in admin → Settings → Scrobbling

# ───────── Acoustic analysis (CLAP audio-similarity + Demucs vocals) ─────────
# The analysis pass (npm run analyze / admin "Analyze audio") computes bpm, key,
# loudness, structure, pace and a beat grid for every track. This runs by
# default in the lean, multi-arch \`analyzer\` sidecar — no config needed.
#
# Two heavier dimensions — CLAP "sounds-like" embeddings and Demucs vocal ranges
# — need a CPU-torch stack that's NOT in the default image. Enable them by
# pulling the heavy analyzer image (a one-liner, no rebuild):
# ANALYZER_HEAVY=1   # switch the \`analyzer\` service to subwave-analyzer-heavy
#
# Don't want the local analyzer container at all — because analysis runs on
# another machine (ANALYZE_URL below), or you don't want acoustic data? Set the
# replica count to zero. The next \`docker compose up -d\` stops and REMOVES the
# container; unset (or empty) means 1, i.e. the default-on station, unchanged.
# ONLY 0 AND 1 ARE VALID: the service pins container_name, which compose refuses
# for more than one replica, so 2 (or a non-integer like \`false\`) fails every
# compose command rather than falling back.
# Compose-only: the AIO one-click image runs the analyzer in-process, so there
# is no container for this to switch off there — blank ANALYZE_PYTHON instead.
# ANALYZER_REPLICAS=0
#
# On NVIDIA hosts, persist the CUDA overlay for all Compose commands:
# COMPOSE_FILE=docker-compose.yml:docker-compose.analyzer-gpu.yml
# For a one-off run, use the two-file command in docs/tts-heavy.md.
# Remove COMPOSE_FILE to return to the CPU analyzer. AIO one-click users should
# use subwave-aio-cuda and pass the GPU to the container; see docs/unraid.md.
#
#
# GPU in a DIFFERENT machine? Run the analyzer there and point the station at
# it — no need to move the stack or copy state around. A same-path state mount
# is optional but faster; it is required for remote
# stem caching. Without one, analysis retries by URL after the path probe:
#   docs/tts-heavy.md#running-the-analyzer-on-another-machine
# ANALYZE_URL=http://192.168.1.101:8080   # overrides the in-compose analyzer
#                                         # pair with ANALYZER_REPLICAS=0 above
#                                         # to drop the redundant local one
# ANALYZE_CONCURRENCY=1  # max in-flight sidecar jobs / worker processes (1-8).
#                        # Default 1 preserves existing behaviour. For a remote
#                        # GPU analyzer, start with 2-4 and set the SAME value on
#                        # both station and GPU hosts. Each worker can load its
#                        # own models, increasing CPU/RAM/VRAM plus network and
#                        # source-server demand; tune to the smaller host limit.
# ANALYZE_PROBE_MS=60000  # how long "no analyzer at all" is cached before the
#                         # /health probe runs again. A backend that ANSWERED is
#                         # remembered until restart; only the miss is timed, so
#                         # an analyzer that comes up after the controller is
#                         # still found within this window. Lower it if you start
#                         # analyzers by hand and want them picked up sooner.
# ANALYZE_DEVICE=    # auto (default) / cpu / cuda — torch device for CLAP/Demucs;
#                    # only meaningful on the cuda analyzer flavour
# ANALYZE_IDLE_UNLOAD_S=  # seconds of no CLAP/Demucs use before the models are
#                         # dropped (0 = keep resident). Defaults per device:
#                         # 300 on cuda (frees the GPU for co-resident TTS/LLM
#                         # between passes), 1800 on cpu (a backfill or sound
#                         # search loads them once and they'd otherwise sit in
#                         # RAM/swap forever; the longer window keeps the cold
#                         # reload off interactive sound searches).
# ANALYZE_RECYCLE_IDLE_S= # sidecar only: seconds of no heavy use before the
#                         # whole worker process is recycled (default 3600;
#                         # 0 = never). The model release above hands back the
#                         # weights; the recycle also reclaims the ~1GB of
#                         # librosa/numba/torch scratch — and on cuda the CUDA
#                         # context — that survive it. Next request re-pays the
#                         # worker boot (a few seconds of imports).
#
# Runtime flags — env wins ON over the admin toggles (settings.audio.*), never
# off. A flag with no matching backend in the image is a clean no-op.
# ANALYZE_AUDIO_EMBEDDING=   # 1/true = fill CLAP audio vectors (needs ANALYZER_HEAVY)
# ANALYZE_VOCAL_ACTIVITY=    # 1/true = fill Demucs vocal ranges (needs ANALYZER_HEAVY)
# ANALYZE_QUIET_ONLY=        # 1/true = pause analysis while anyone is listening;
#                            # resumes after settings.audio.analyzeQuietMinutes
#                            # (default 10) with no listeners (#1099)
#
# Building from source instead of pulling? \`docker compose build analyzer\` with
# ANALYZER_HEAVY=1 bakes the stack (or pass WITH_CLAP=1 / WITH_DEMUCS=1 directly).
#
# Vocal-gate tuning (#1125). The Demucs vocal stem is thresholded against BOTH
# its own loud level AND a fraction of the FULL-MIX loud level — the mix floor
# stops separation bleed on instrumentals from reading as vocals. Raise the
# floor if instrumentals still slip through (over-compressed masters leak more);
# lower it if quiet vocals get dropped. Defaults shown.
# VOCAL_MIX_FLOOR=0.06     # vocal stem must reach >=6% of the full-mix loud level
# VOCAL_STEM_REL=0.15      # ...OR >=15% of the vocal stem's own loud level
#
# Optional model overrides (sensible defaults shown):
# CLAP_MODEL=laion-clap
# DEMUCS_MODEL=htdemucs   # vocal separation is the slow pass, and the default
#                         # is also the fastest on CPU we've measured — the
#                         # mdx*/*_q alternatives are bags of 4 sub-models and
#                         # run ~3x SLOWER despite the smaller download
# ANALYZE_SECONDS=40      # per-track analysis window (seconds), shared by
#                         # bpm/key, CLAP and Demucs — the real speed lever
#                         # (cost scales linearly). Raise it if you want vocal
#                         # ranges detected deeper into each track
# ANALYZE_CLAP_WINDOWS=3  # how many windows the CLAP "sounds-like" embed
#                         # averages over (1-3). 3 = start/mid/late (default,
#                         # best vectors), 1 = leading window only (fastest,
#                         # the pre-multi-window behaviour). CLAP cost per
#                         # track scales linearly with this
# ANALYZE_OUTRO_SECONDS=20 # tail window (seconds) decoded from the END of each
#                         # complete file for outro analysis (fade-vs-cold
#                         # ending, tail loudness/tempo — drives the
#                         # ending-aware crossfade). Pure librosa, cheap
#
# Which heavy-TTS engines the tts-heavy sidecar loads. Chatterbox AND PocketTTS
# are both baked into the image, but each costs RAM + a first-boot weight
# download + startup time — so if you only use one, name it here and the other
# never loads. Comma-separated; default loads both. Only matters with
# --profile tts-heavy.
# TTS_HEAVY_ENGINES=pocket-tts     # or: chatterbox  |  chatterbox,pocket-tts
#
# How long an idle heavy-TTS engine stays loaded. Chatterbox is ~4GB resident
# (weights, plus torch's CUDA context on a GPU host) and used to be held for
# the life of the container whether or not the station had spoken all day —
# the programme's idle pause stands the music down but has no reach into the
# sidecar. After this many seconds without a spoken line the sidecar stops
# that engine's worker and hands the memory back, reloading it on the next
# line — or ahead of one, since the controller warms the sidecar both when the
# programme's idle pause releases and when the DJ decides to talk. The first
# of those hides the reload completely but needs the idle pause switched ON
# (Settings -> Stream, off by default); with it off you get only the second,
# which overlaps the load with writing the script, so part of a cold reload is
# still audible as a longer gap before the first line. Empty = 1800 on cuda,
# 3600 on cpu; both sit far above any gap a talking station produces, so this
# only fires when the station really has gone quiet. 0 keeps the old
# always-resident behaviour — worth it if you have RAM to spare and never want
# a cold reload. Per-engine overrides win over the shared value. Only matters
# with --profile tts-heavy.
# TTS_HEAVY_IDLE_UNLOAD_S=1800
# CHATTERBOX_IDLE_UNLOAD_S=      # just Chatterbox (the expensive one)
# POCKET_TTS_IDLE_UNLOAD_S=0     # e.g. keep the small, fast engine resident
#
# Seconds /speak waits for a cold engine to load before giving up and letting
# the DJ fall through to its rescue voice. Raise it on a slow disk or a first
# load that still has weights to fetch; the ceiling has to leave room inside
# TTS_HEAVY_TIMEOUT_MS (180000) for the render that follows. This is only a
# CEILING — a load the sidecar abandons sooner (missing venv, fatal model
# error) fails its caller straight away. Floored at 5; anything unparseable is
# ignored with a warning rather than stopping the sidecar booting.
# TTS_HEAVY_LOAD_TIMEOUT_S=90
#
# Fallback Chatterbox reference WAV, used only for a line whose persona has no
# voice of its own (a persona voice always wins). The path is read INSIDE the
# container, so put the file under the shared state mount and name it there —
# /var/sub-wave/voices/<file>.wav. Only matters with --profile tts-heavy; the
# all-in-one image reads the same variable for its in-process Chatterbox.
# CHATTERBOX_REFERENCE_WAV=/var/sub-wave/voices/house.wav
#
# Own TTS server? There's nothing to set here — the *Remote* engine points the
# DJ at any HTTP server that answers GET /health and returns rendered audio from
# POST /speak (a GPU box, a Tailscale peer, a bridge in front of a vendor API
# like Gemini TTS). It's a station setting, not env: admin → Settings → Voices →
# Remote. Contract + a 20-line reference server: docs/custom-tts.md
#
# Memory ceilings for the model-loading sidecars (OOM containment — keeps a
# runaway model load from taking down the host's other services). Defaults are
# generous; raise for the heavy analyzer on large libraries, lower on a
# constrained host. TTS_HEAVY_MEM_LIMIT only matters with --profile tts-heavy.
# ANALYZER_MEM_LIMIT=6g
# TTS_HEAVY_MEM_LIMIT=10g
#
# HuggingFace token — lets the tts-heavy sidecar lazily download gated model
# weights at runtime (PocketTTS cloning weights; some CLAP/Demucs checkpoints).
# HF_TOKEN=
`;

// cli/package.json#version (embedded so the compiled binary can self-identify
// — used by `subwave --version`).
export const CLI_VERSION = `1.13.0`; // x-release-please-version
